version: '3'
services:
  
  openresty:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/geoip_db.mmdb:/usr/bin/geoip_db.mmdb
  
  us_1:
    build: ./app
    command: ["python", "app.py", "--server_name", "US Server 1"]
    ports:
      - 5000:5000
  us_2:
    build: ./app
    command: ["python", "app.py", "--server_name", "US Server 2"]
    ports:
      - 5001:5000

  uk_1:
    build: ./app
    command: ["python", "app.py", "--server_name", "UK Server"]
    ports:
      - 5002:5000

  default_1:
    build: ./app
    command: ["python", "app.py", "--server_name", "Default Server"]
    ports:
      - 5003:5000
  
  backup_1:
    build: ./app
    command: ["python", "app.py", "--server_name", "Backup Server"]
    ports:
      - 5004:5000

  